### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by chemnic** [lohanitech/openpics#1]
First: Great app!

What about proxy support?

I'm testing with Ubuntu 14.04. The app doesn't seem to use the proxy environment variables. And it doesn't have a settings option for it.

Thank you.

**Comment by lohanidamodar** [comment]
Hi, Thanks!
I didn't think the need of proxy support as the app was working fine.
It would be great if you would like to help with this?

Thank you

**Comment by chemnic** [comment]
Unfortunately I'm not a developer. But I can do testing if someone else do it.

Anyway, I'm using the app in a VM without proxy for now.

**Comment by lohanidamodar** [comment]
Thanks!
Will let you know, if we work on proxy support anytime soon
